### ISSUE TITLE
Can't upload picture when creating new product

### ISSUE THREAD

**Issue by amejiarosario** [amejiarosario/meanshop#1]
**Steps to reproduce**
1. Login
2. `/products/new`
3. Add new product data
4. Upload a picture
* Notice that the picture doesn't get saved.

**Workarounds**
- Create new product without picture
- Then click `edit` and upload a picture. It will works this time

**Comment by Ariful-Haque** [comment]
Inside your product.controller.js file,  'uploadHandler' is mistakenly put into 'ProductEditCtrl'. It should be inside 'ProductNewCtrl'. Remove the dependencies and $scope.upload..... and put it inside 'ProductNewCtrl' controller. It will solve the problem.

.controller('ProductNewCtrl', function ($scope, $state, Product, Upload, $timeout) {
    $scope.product = {}; // create a new instance
    $scope.addProduct = function(){
      Products.save($scope.product,
        function success(value /*, responseHeaders*/){
          $state.go('viewProduct', {id: value._id});
        }, errorHandler($scope));
    };
    $scope.upload = uploadHander($scope, Upload, $timeout);
  })

**Comment by amejiarosario** [comment]
There are some issues with that approach. If I move uploadHandler to ProductNewCtrl... it will try to save the picture before the product is even created. I'm just go it working by uploading the picture after the file is created in a callback

**Comment by powolnymarcel** [comment]
As a user I want to upload the product's picture at the same time as the product is created not after... It should be a one step process...

**Comment by amejiarosario** [comment]
Yes, I agree. It will one step process from the user perspective. Behind the scenes it would be two immediate calls: one to create the object, validation and get the _id, and second one to upload the file to the given product.

**Comment by powolnymarcel** [comment]
No offense but this is what I was expecting before buying your book. Overall it's a great book to learn MEAN but there is this small "stain".

**Comment by amejiarosario** [comment]
This little stain has been clear out, I will continue with the other ones
