### ISSUE TITLE
Unable to update the image

### ISSUE THREAD

**Issue by wakakokorosensei** [amejiarosario/meanshop#14]
Hello I bought his book very interesting, but there is a problem in the upload image.
I created a new product, I go to edit upload the image and save the product, but then it is impossible to change the image. 
Debugging the application I noticed that, when I get another picture, uploadHander updates the DB, but then when saved, the DB is again updated with the previous image

**Comment by amejiarosario** [comment]
@wakakokorosensei fixed on master

**Comment by wakakokorosensei** [comment]
Thank you very much
