### ISSUE TITLE
fix installation instructions of the first chapter of the book

### ISSUE THREAD

**Issue by dportabella** [amejiarosario/meanshop#29]
Following the instructions of the first chapter of [the associated book](http://shop.oreilly.com/product/9781785286551.do), results in several errors:

It's missing at page 6:
`$ npm install -g yo
`

It's missing at page 8:
```
$ npm install -g grunt-cli
# Install dependencies for grunt-contrib-sass. Instructions: https://github.com/gruntjs/grunt-contrib-sass
$ npm install -g bower
$ bower install
```

I didn't find a place in the oreilly website to provide feedback about your book. should I write here comments about the book, or somewhere else?

**Comment by ericmontreal** [comment]
@dportabella  Thx ! I searched for these info.

Still, on page 8`grunt serve` command required Ruby and Sass installed to completely app build app.

**Comment by dportabella** [comment]
about "ruby and sass", this is what i mentioned with:
`# Install dependencies for grunt-contrib-sass. Instructions: https://github.com/gruntjs/grunt-contrib-sass`

**Comment by ericmontreal** [comment]
Oops!  I skipped your comment...
:) 
Otherwise, I still get some non-blocking
> Missing option 'template', using 'dest' as template instead
 messages.

I now get the master branch running but can't find a way to add any new item despite what's mentionned page 22 (line 16)
:(

**Comment by dportabella** [comment]
I see that there are some typos in the book. I see that the code here in github has many branches (ch1, ch2, ch3...), and it seems that they all work (no typos). So, whenever I find a type on the book, I just clone this repo and checkout the branch.

**Comment by ericmontreal** [comment]
Yes. I wrongly supposed master branch was the full project. I wonder which release author refers to when he writes p.22:

> Interact with the app for a few minutes (http://localhost:9000). Open 
> another window with the application. Add a new item and notice that this 
> too gets updated in all the browser windows in real-time. Pretty cool, huh?

**Comment by Legited** [comment]
@ericmontreal that's referring to the default template that comes with angular-fullstack scaffold (the to-do type of list)

**Comment by ericmontreal** [comment]
OK I see now.Thx Legited !!
I'd better download zip file rather than checking out versions...

**Comment by amejiarosario** [comment]
Thanks for the feedback. I updated the installation instructions on the readme: https://github.com/amejiarosario/meanshop/blob/master/README.md
