### ISSUE TITLE
Why you create a product service and call it 'Product', instead of 'ProductService'?

### ISSUE THREAD

**Issue by dportabella** [amejiarosario/meanshop#31]
In products.service.js you create a service named 'Product'. Why? it is a service, not a product. This name is totally misleading. It should be called ProductService.

https://github.com/amejiarosario/meanshop/blob/master/client/app/products/products.service.js
```
angular.module('meanshopApp')
  .factory('Product', function ($resource, $timeout, Upload, $q) {

```

**Comment by amejiarosario** [comment]
It's some kind of convention (see below some references). The name of the file states it is a service: `products.service.js`. In the code, you can tell if is a service or an instance by the capitalization...

``` javascript
// https://github.com/amejiarosario/meanshop/blob/master/client/app/products/products.controller.js#L8
var products = Product.query();
```
You can tell the service always starts with uppercase while the instance is on lower case.

If you take a look at the [Angular source code](https://docs.angularjs.org/api/ng/service) itself you will notice they don't use `Service` suffix. Neither on popular AngularJS guides like [this one](https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md#style-y040). 

See:
 - https://docs.angularjs.org/api/ng/service
 - https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md#style-y040

**Comment by dportabella** [comment]
I found several cases using the `Service` suffix in the [popular AngularJS you mention](https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md):

```
        var hero = avengerService.find(vm.heroSearch);
        return avengersService.getAvengers()
       return creditService.isOrderTotalOk(vm.total)
    movieService.getMovies().then(function(response) {
    vm.movies = moviesPrepService.movies;
    vm.refresh = sessionDataService.refresh;
```
