### ISSUE TITLE
Is there any reason why in exampleProducts you prefix the id with an underscore?

### ISSUE THREAD

**Issue by dportabella** [amejiarosario/meanshop#32]
Is there any reason why in `exampleProducts` you prefix the id with an underscore (`_id` instead of simply `id`)?

https://github.com/amejiarosario/meanshop/blob/ch2/client/app/products/products.service.js

```
angular.module('meanshopApp')
  .factory('Product', function () {
    var exampleProducts = [
      {_id: 1, title: 'Product 1', price: 123.45, quantity: 10, description: 'Lorem ipsum dolor sit amet'},

```

**Comment by Legited** [comment]
@dportabella a document in mongoDB is also referred to by _id parameter, which is generated automatically. When you create a new document in your database and then look at its parameters by running db.{collection}.find()   each document will start with _id parameter

**Comment by dportabella** [comment]
ok, I see. it was a bit confusing because monodb is not yet introduced in chapter 2, so I was wondering if it had to do anything about angularjs.
thx.
