### ISSUE TITLE
webserver is down for a bug in one request?

### ISSUE THREAD

**Issue by dportabella** [amejiarosario/meanshop#33]
I checkout this meanshop repository and I forget to configure the braintree payment. I run the server with `grunt serve`, and I can browse successfully the pages about catalog. If I click on the cart, then there is a server error:
```
/Users/david/webdev/meanshop/server/api/braintree/braintree.controller.js:33
    return handleResponse(res)(err, data.clientToken);
                                        ^
TypeError: Cannot read property 'clientToken' of null
    at /Users/david/webdev/meanshop/server/api/braintree/braintree.controller.js:33:41

```
and now all the webserver is down; I cannot browse the pages about catalog as before.

only because of a bug in one page, the whole webserver is now down.
I think this is not acceptable.
what do you think?

**Comment by amejiarosario** [comment]
I agree. It should recover from missing configs. I'll fix it, also feel free to send a `pull request` with a fix if you already have it. Thanks

**Comment by dportabella** [comment]
the question was more general; it should not only recover from missing configs, it should also recover from bugs. You could fix your program to check the missing configs and abort launching the webserver or show an error page when using that feature. But it is impossible to have a source code free of bugs; it is not acceptable that the webserver goes down because there is one bug in one of the pages/features. I guess that this is an issue about NodeJs/ExpressJs itself. What do you think about it?

**Comment by amejiarosario** [comment]
Ok, I understand. That only happens in development though. On chapter 10 (page 166), for deployment we use [pm2](https://github.com/Unitech/pm2). This package, will bring up the server again after crashes failures. Also, [forever](https://github.com/foreverjs/forever) does a similar thing... keeps node running forever.

**Comment by cosjef** [comment]
If we wanted to use Forever to do this, what is the proper command line for meanshop?

$ forever start <some.js_file)

The syntax cannot be "forever start grunt serve," right? Which .js file do we point Forever to?

**Comment by amejiarosario** [comment]
You can use:
```
# start process in the background
forever start server/index.js

# list processes running and see UID
forever list

# stop process
forever stop UID
```
