### ISSUE TITLE
some duplicated code

### ISSUE THREAD

**Issue by dportabella** [amejiarosario/meanshop#35]
`catalog.events.js` is identical to `product.events.js` (just changing the variable names).
same for `catalog.socket.js` and `product.sockets.js`.
and a big part also for `catalog.controller.js` and `product.controller.js`.

how would you best remove such duplication?

**Comment by amejiarosario** [comment]
`catalog.events.js`, `product.events.js`, `catalog.socket.js`, and  `product.sockets.js` were autogenerated by the `angular-fullstack` generator and hasn't been changed. I'm planning to use them in the future so I leave them there.

Also `catalog.controller.js` and `product.controller.js` were autogenerated but throughout the book they are changed based on their individual needs. I agree they still have a number methods that are repeated in both places. I'd remove the duplication by creating a `helper` library were I can define common functions and use it wherever needed.

**Comment by dportabella** [comment]
ok
