### ISSUE TITLE
this.$index

### ISSUE THREAD

**Issue by dportabella** [amejiarosario/meanshop#37]
in chapter 10 "Planning a new feature", you have this sample:

at admin.controller.js, you have:
```
    $scope.deleteUser = function(user) {
      User.remove({ id: user._id });
      $scope.users.splice(this.$index, 1);
    };

```
and admin.html
```
      <tr ng-repeat="user in users">
          <a ng-click="deleteUser(user)"><i class="fa fa-2x fa-trash-o"></i></a>
      </tr>

```

what is `this` here? it represents a context inside the repeat loop?
can you explain more about `this.$index`?

**Comment by amejiarosario** [comment]
In `admin.html` we are using `ngRepeat` which defines a number of special properties such as `$index`, `$first`, `$last`...

`this.$index` refers to the index matching the current `user` on the array of `users`. In this case `this` refers to the current scope. For more [read here](http://stackoverflow.com/a/14168699/684957).

**Comment by dportabella** [comment]
I see. thanks!
