### ISSUE TITLE
npm dependencies

### ISSUE THREAD

**Issue by dportabella** [amejiarosario/meanshop#40]
in the book, Chapter1, "Installing the MEAN component":
you explain to install several dependencies.

these ones, you install them globally. I understand, because when someone clones your already-inplemented project, he does not need those, as they are used to create the scaffolder.
`npm install -g yo`
`npm install -g generator-angular-fullstack`

however, you install these two globally, and they are needed for development. so, if someone clones your project, he will fail to build/run it without them. Why you don't install them locally with --save-dev?
`npm install -g grunt-cli`
`npm install -g bower`

and this one, you install it globally, but it is used in production. so why not install it locally with --save?
`npm install -g express`

**Comment by amejiarosario** [comment]
Good point. I added bower to dev-dependencies. 

About `grunt`, it is already listed as a dev-dependency. Howerver, following [Grunt instructions](http://gruntjs.com/getting-started) you need to install globally `grunt-cli` which links to whatever version of grunt you have on the project
