### ISSUE TITLE
npm warns deprecated packages

### ISSUE THREAD

**Issue by ayaancoder** [amejiarosario/meanshop#42]
update commands in Ecommerce with meanstack book

**Comment by amejiarosario** [comment]
@ayaancoder please list the deprecated packages you are referring to

**Comment by ayaancoder** [comment]
After running this  command with sudo npm install -g generator-angular-fullstack@3.0.0-rc4

this is listed deprecated packages
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

**Comment by amejiarosario** [comment]
Thanks, I'm creating a new branch using the latest packages. I'll merge it with master when ready.
