### ISSUE TITLE
After chapter one this is the issue

### ISSUE THREAD

**Issue by ayaancoder** [amejiarosario/meanshop#44]
![products page](https://cloud.githubusercontent.com/assets/16849115/15772545/980e4594-2969-11e6-8650-34903274eca4.png)
![meanshop home page](https://cloud.githubusercontent.com/assets/16849115/15772546/980f2d74-2969-11e6-88bf-a47d11666c7e.png)

**Comment by amejiarosario** [comment]
Are you getting any error in the logs? or browser console?

**Comment by Carmezim** [comment]
Had the exact same issue.

**Comment by amejiarosario** [comment]
Ok, you can checkout the `ch1` branch. It's what you should have at the end of the chapter. Try this:

```
# get chapter 1
git checkout ch1

# install deps
npm install && bower install

# run app
grunt serve
```

Then you can compare what were you missing...
