### ISSUE TITLE
Fixed the File upload issue

### ISSUE THREAD

**Issue by stanjhae** [amejiarosario/meanshop#47]
<img width="921" alt="screen shot 2016-08-03 at 12 19 16 am" src="https://cloud.githubusercontent.com/assets/13360830/17347410/03656950-5910-11e6-8703-87bf54238994.png">
<img width="961" alt="screen shot 2016-08-02 at 11 56 30 pm" src="https://cloud.githubusercontent.com/assets/13360830/17347411/0365cc7e-5910-11e6-86ca-231f025974d5.png">

This fixes the issue with uploading a picture and editing it.

**Comment by amejiarosario** [comment]
Thanks, that has been fixed in the master branch already #19. It's similar to what you did see: https://github.com/amejiarosario/meanshop/pull/19/files
