### ISSUE TITLE
Error during Grunt serve

### ISSUE THREAD

**Issue by raw-at** [amejiarosario/meanshop#53]
![image](https://cloud.githubusercontent.com/assets/20211990/22401568/312efb72-e5ff-11e6-8a99-c4974ebf90b7.png)

Error coming Cannot find module './api   hing/'

**Comment by amejiarosario** [comment]
@raw-at Most likely you have a typo on `server/routes.js` line 13.

You should have
```
  app.use('/api/things', require('./api/thing'));
```

Do you have this instead?
```
  app.use('/api/things', require('./api        hing'));
```

If not, then since you are using **Windows** it might be confusing `\t` on `\things` as a tab...

try

```
  app.use('/api/things', path.join('.', 'api', 'things'));
```

Let me know if that helps

**Comment by raw-at** [comment]
Yup there was \t in place of /t in the line
app.use('/api/things', require('./api        hing'));

Thanx for help :)
